1:
  robot1:
    window_x: 0
    window_y: 0
    window_width: 1280
    window_height: 720

2:
  robot1:
    window_x: 0
    window_y: 0
    window_width: 1280
    window_height: 720
  robot2:
    window_x: 100
    window_y: 100
    window_width: 1280
    window_height: 720

3:
  robot1:
    window_x: 0
    window_y: 0
    window_width: 1280
    window_height: 720
  robot2:
    window_x: 100
    window_y: 100
    window_width: 1280
    window_height: 720
  robot3:
    window_x: 200
    window_y: 200
    window_width: 1280
    window_height: 720